export {};
export { default as LoadingImg } from "./image 129.png";
export { default as LolImg } from "./image 71.png";
export { default as OverWatchImg } from "./image 72.png";
export { default as LostArkImg } from "./image 73.png";
export { default as ValorantImg } from "./image 74.png";
export { default as NetflixImg } from "./image 81.png";
export { default as WatchaImg } from "./image 80.png";
export { default as TvingImg } from "./image 82.png";
export { default as DisneyImg } from "./image 83.png";
